version: '3.8'

services:
  # Development overrides
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app
      - /app/.venv  # Exclude virtual environment
    environment:
      DEBUG: "True"
      ENVIRONMENT: development
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:20-alpine
    container_name: mcp_scanner_frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Exclude node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0